-- Create xp_log table if not exists
create table if not exists xp_log (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users on delete cascade not null,
  task_id bigint references tasks on delete cascade,
  xp_earned integer not null,
  source text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table xp_log enable row level security;

-- Create policies for xp_log
create policy "Users can view their own xp logs."
  on xp_log for select
  using ( auth.uid() = user_id );

create policy "System can insert xp logs."
  on xp_log for insert
  with check ( true );

-- Create index for faster queries
create index if not exists xp_log_user_id_idx on xp_log(user_id);
create index if not exists xp_log_created_at_idx on xp_log(created_at); 